
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set-up,include=F}
# Loading libraries
library(tidyverse)
library(ggplot2)
library(janitor)
library(stringr)
library(lubridate)
library(stringi)
library(patchwork)
library(gganimate)
install.packages("googleVis")
```


```{r data wrangling, echo=F}
# Loading dataset
load("raw-data/odimetadata.Rdata")
#Adding year and over variables
subset <- 
  results %>%
  mutate(year = year(as.Date(
  date, format = "%m/%d/%Y"))) %>%
  mutate(over = stri_extract(ball, regex = "[.](.*)")) %>%
  mutate(over = substring(over, 2)) %>%
  mutate(over = gsub("\\..*","", over)) 
```

```{r lastfive}
data <- subset %>% 
  na.omit(totalRuns) %>%
  mutate(phase = case_when(
    over %in% 0:10 ~ "First Ten",
    over %in% 10:25  ~ "First Middle",
    over %in% 25:40 ~ "Second Middle",
    over %in% 40:50 ~ "Last Ten")) %>%
    group_by(phase, column_label) %>%
    mutate(phase_runs = sum(totalRuns)) %>%
    ungroup() %>%
    mutate(bracket = case_when(
    phase_runs %in% 0:25 ~ "Less than 25 Runs",
    phase_runs %in% 25:75  ~ "25 to 75 Runs",
    phase_runs %in% 75:150 ~ "75 to 150 runs",
    phase_runs >150 ~ "More than 150 Runs")) %>%
    group_by(year, phase) %>%
    mutate(average_runs = mean(phase_runs)) %>%
    ungroup() %>%
    group_by(bracket, year) %>%
    mutate(win = ifelse(winner=="Australia",1,0)) %>%
    mutate(prop_won = sum(win)/n()) %>%
    ungroup()

```


```{r plot1}
# Making plot of the proportion of matches won by 
# Pakistan within each run bracket sorted according
# to the year the match was played 
p1 <- 
  data %>%
  filter(phase=="First Ten") %>%
  ggplot() +
  geom_point(aes(x = factor(year), 
                 group = factor(bracket), 
                 color = factor(bracket), y = prop_won), 
                 size=2) +
    labs(title = 
         "Proportion of Matches won by Pakistan Sorted by Runs Scored in the \n First Five Overs", 
    subtitle = "Sorted According to Run Bracket - Period: 2010-2017",
    x = "Year", 
    y = "Proportion Won",
    col = "Runs Scored Bracket") +
    labs(caption = "Source: cricsheet.org") +
    theme_classic()+ 
    theme(legend.position = "right",
    axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r plot2}
# Making plot of the proportion of matches won by 
# Pakistan within each run bracket sorted according
# to the year the match was played 
p2 <- 
  data %>%
  filter(phase=="Last Ten") %>%
  ggplot() +
  geom_point(aes(x = factor(year), 
                 group = factor(bracket), 
                 color = factor(bracket), y = prop_won), 
                 size=2) +
    labs(title = 
         "Proportion of Matches won by Pakistan Sorted by Runs Scored in the \n Last Five Overs", 
    subtitle = "Sorted According to Run Bracket - Period: 2010-2017",
    x = "Year", 
    y = "Proportion Won",
    col = "Runs Scored Bracket") +
    labs(caption = "Source: cricsheet.org") +
    theme_classic()+ 
    theme(legend.position = "right",
    axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r plot3}
# Making plot of the proportion of matches won by 
# Pakistan within each run bracket sorted according
# to the year the match was played 
data %>%
  group_by(year, phase) %>%
  summarize(average_runs = mean(average_runs)) %>%
  ggplot(aes(x = factor(year), 
                 y = average_runs,
             group=phase,
             color=phase)) +
  geom_line() +
    labs(title = 
         "Runs Scored in Each Phase", 
    subtitle = "Period: 2010-2017",
    x = "Year", 
    y = "Average Runs",
    col = "Innings Phase") +
    labs(caption = "Source: cricsheet.org") +
    theme_classic()+ 
    theme(legend.position = "right",
    axis.text.x = element_text(angle = 45, hjust = 1)) +
  transition_reveal(year)
```


```{r}
p1+p2+plot_layout(ncol=1)
```



